### Авторизация
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
	"username": "admin",
	"password": "admin123"
}

### Проверка авторизации
GET http://localhost:8000/api/v1/users/me/

### Создание ника
POST http://localhost:8000/api/v1/clients/nicknames
Content-Type: application/json

{
	"nickname": "winner1"
}

### Проверка созданного ника
GET http://localhost:8000/api/v1/clients/nicknames/2

### Изменение ника
PUT http://localhost:8000/api/v1/clients/nicknames/2
Content-Type: application/json

{
    "nickname": "winner1-edit"
}

### Удаление ника
DELETE http://localhost:8000/api/v1/clients/nicknames/2



### Создание ссылки
POST http://localhost:8000/api/v1/clients/urls
Content-Type: application/json

{
	"url": "https://t.me/tanf93"
}

### Проверка созданной ссылки
GET http://localhost:8000/api/v1/clients/urls/2

### Изменение ссылки
PUT http://localhost:8000/api/v1/clients/urls/2
Content-Type: application/json

{
    "url": "https://t.me/tanf92"
}

### Удаление ссылки
DELETE http://localhost:8000/api/v1/clients/urls/2



