"""Create orders & order_files tables

Revision ID: db8b5415c057
Revises: e106f2e976b0
Create Date: 2023-01-20 09:40:17.689890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8b5415c057'
down_revision = 'e106f2e976b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False, comment='Путь к файлу'),
    sa.Column('upload_ts', sa.TIMESTAMP(), nullable=False, comment='Дата загрузки'),
    sa.Column('is_result', sa.Boolean(), nullable=True, comment='Файл относится к результатам?'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_files_id'), 'order_files', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tz', sa.Text(), nullable=True, comment='Текст тз'),
    sa.Column('start_ts', sa.TIMESTAMP(), nullable=False, comment='Дата создания заказа'),
    sa.Column('deadline_ts', sa.TIMESTAMP(), nullable=False, comment='Дата дедлайна'),
    sa.Column('end_ts', sa.TIMESTAMP(), nullable=True, comment='Дата завершения работы'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Комментарий к заказу'),
    sa.Column('cost', sa.Integer(), nullable=False, comment='Стоимость работы'),
    sa.Column('spent_hours', sa.Integer(), nullable=True, comment='Затраченное время'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Статус заказа'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('order_changes_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='Id заказа'),
    sa.Column('text', sa.Text(), nullable=True, comment='Текст изменения'),
    sa.Column('create_ts', sa.TIMESTAMP(), nullable=False, comment='Дата создания изменения'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Статус заказа'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_changes_history_id'), 'order_changes_history', ['id'], unique=False)
    op.create_index(op.f('ix_order_changes_history_order_id'), 'order_changes_history', ['order_id'], unique=False)
    op.create_table('orders_order_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Id заказа'),
    sa.Column('change_id', sa.Integer(), nullable=True, comment='Id изменения'),
    sa.Column('order_file_id', sa.Integer(), nullable=True, comment='Id файла'),
    sa.ForeignKeyConstraint(['change_id'], ['order_changes_history.id'], ),
    sa.ForeignKeyConstraint(['order_file_id'], ['order_files.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_files_id'), 'orders_order_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_files_id'), table_name='orders_order_files')
    op.drop_table('orders_order_files')
    op.drop_index(op.f('ix_order_changes_history_order_id'), table_name='order_changes_history')
    op.drop_index(op.f('ix_order_changes_history_id'), table_name='order_changes_history')
    op.drop_table('order_changes_history')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_files_id'), table_name='order_files')
    op.drop_table('order_files')
    # ### end Alembic commands ###
