"""Change table names

Revision ID: ea44ca41c1a2
Revises: 216c95952af0
Create Date: 2023-01-04 21:21:05.684952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea44ca41c1a2'
down_revision = '216c95952af0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_clients_urls',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['clients_urls.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'url_id')
    )
    op.drop_table('client_client_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_client_urls',
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='client_client_urls_client_id_fkey'),
    sa.ForeignKeyConstraint(['url_id'], ['clients_urls.id'], name='client_client_urls_url_id_fkey'),
    sa.PrimaryKeyConstraint('client_id', 'url_id', name='client_client_urls_pkey')
    )
    op.drop_table('clients_clients_urls')
    # ### end Alembic commands ###
