name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --indent-string='\t' --ignore-paths=alembic,tests \
        --disable=fixme,invalid-name,missing-docstring,too-few-public-methods,\
        unused-argument,protected-access,no-self-use,relative-beyond-top-level,\
        no-self-argument,import-error,redefined-builtin,no-value-for-parameter,\
        raise-missing-from --fail-under=9
