name: Pytest

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: docker-compose up
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose up -d
      - name: Check running containers
        run: docker-compose ps -a
      - name: Check logs
        run: docker-compose logs app
      - name: Test with pytest
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec web pytest
